#!/usr/bin/env zsh
export ZPOOL=nvm

export LITECOIN_HOME=/litecoin
export LITECOIN_USER=litecoin
export LITECOIN_GROUP=litecoin

# create /litecoin/socket with custom ACL for electrs unix sockets
zfs create -o "mountpoint=${LITECOIN_HOME}/socket" "${ZPOOL}/litecoin/socket"

setfacl -m "user:litecoin:full_set:f:allow,user:mempool:full_set:f:allow,user:www:full_set:f:allow,everyone@::f:allow" "${LITECOIN_HOME}/socket"

chown "${LITECOIN_USER}:${LITECOIN_GROUP}" "${LITECOIN_HOME}/socket"
