#!/usr/bin/env zsh

# initialize variables
DAEMON=litecoin
NETWORK=mainnet
FEATURES=default
DB_FOLDER=/electrs
NODENAME=$(hostname|cut -d . -f1)
LOCATION=$(hostname|cut -d . -f2)
USAGE="Usage: $0 (mainnet|testnet|signet)"

# load rust if necessary
if [ -e "${HOME}/.cargo/env" ];then
	source "${HOME}/.cargo/env"
	export PATH="${HOME}/.cargo/bin:${PATH}"
fi

# which OS?
case "$(uname -s)" in
	FreeBSD)
		OS=FreeBSD
		NPROC=$(sysctl -n hw.ncpu)
		export CC=/usr/local/bin/clang17
		export CXX=/usr/local/bin/clang++17
		export CPP=/usr/local/bin/clang-cpp17
		export RUSTFLAGS="-C linker=clang17"
	;;
	Darwin)
		OS=Darwin
		NPROC=$(sysctl -n hw.ncpu)
	;;
	Linux)
		OS=Linux
		NPROC=$(grep -c proc /proc/cpuinfo)
	;;
	*)
		OS=Unknown
		NPROC=4
	;;
esac

# which network?
case "${1}" in
	mainnet)
		THREADS=$((NPROC / 8))
	;;
	testnet)
		NETWORK=testnet
		THREADS=$((NPROC / 8))
	;;
	signet)
		NETWORK=signet
		THREADS=$((NPROC / 8))
	;;
	*)
		echo "${USAGE}"
		exit 1
	;;
esac

case "${2}" in
	version)
		echo "[*] Only print versions, then exit"
		cargo run --bin electrs --release -- --version
		exit 0
	;;
	"")
		# If the 2nd arg isn't passed, just run the normal electrs script as-is
	;;
	*)
		echo "${USAGE}"
		exit 1
	;;
esac

# run in loop in case of crash
until false
do
	# reset CWD
	cd "${HOME}/electrs"

	# disable making electrs.core files
	ulimit -c 0

	# prepare run-time variables
	UTXOS_LIMIT=500
	ELECTRUM_TXS_LIMIT=500
	ELECTRUM_MAX_LINE_SIZE=1048576 # 1 MiB
	ELECTRUM_MAX_SUBSCRIPTIONS=100
	ELECTRUM_MAX_CLIENTS=10
	MAIN_LOOP_DELAY=500
	DAEMON_CONF="${HOME}/${DAEMON}.conf"
	HTTP_SOCKET_FILE="${HOME}/socket/esplora-${DAEMON}-${NETWORK}"
	RPC_SOCKET_FILE="${HOME}/socket/electrum-${DAEMON}-${NETWORK}"

	# get RPC credentials from litecoin.conf directly
	echo "[*] Getting RPC credentials from ${DAEMON_CONF}"
	RPC_USER=$(grep 'rpcuser=' "${DAEMON_CONF}"|cut -d = -f2|head -1)
	RPC_PASS=$(grep 'rpcpassword=' "${DAEMON_CONF}"|cut -d = -f2|head -1)

	# override limits based on hostname
	if [ "${NODENAME}" = "node201" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
		MAIN_LOOP_DELAY=14000
	fi
	if [ "${NODENAME}" = "node204" ] && [ "${LOCATION}" = "sg1" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node204" ] && [ "${LOCATION}" = "hnl" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node206" ] && [ "${LOCATION}" = "tk7" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node211" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node212" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node213" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${NODENAME}" = "node214" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi
	if [ "${LOCATION}" = "fmt" ];then
		UTXOS_LIMIT=9000
		ELECTRUM_TXS_LIMIT=9000
		ELECTRUM_MAX_LINE_SIZE=16777216 # 16 MiB
		ELECTRUM_MAX_SUBSCRIPTIONS=100000
		ELECTRUM_MAX_CLIENTS=10000
	fi

	# Run the electrs process (Note: db-dir is used in both commands)
	nice cargo run \
		--release \
		--bin electrs \
		--features "${FEATURES}" \
		-- \
		--network "${NETWORK}" \
		--daemon-dir "${HOME}" \
		--db-dir "${DB_FOLDER}" \
		--main-loop-delay "${MAIN_LOOP_DELAY}" \
		--rpc-socket-file "${RPC_SOCKET_FILE}" \
		--http-socket-file "${HTTP_SOCKET_FILE}" \
		--precache-threads "${THREADS}" \
		--cookie "${RPC_USER}:${RPC_PASS}" \
		--cors '*' \
		--address-search \
		--utxos-limit "${UTXOS_LIMIT}" \
		--electrum-txs-limit "${ELECTRUM_TXS_LIMIT}" \
		--electrum-max-line-size "${ELECTRUM_MAX_LINE_SIZE}" \
		--electrum-max-subscriptions "${ELECTRUM_MAX_SUBSCRIPTIONS}" \
		--electrum-max-clients "${ELECTRUM_MAX_CLIENTS}" \
		-vv
	sleep 1
done
